### ISSUE TITLE
NullPointerException on Windows

### ISSUE THREAD

**Issue by JAAdrian** [jebej/MatlabWebSocket#1] opened 2015-06-22 14:36 UTC
Hi,

thanks for the great code!
But I get a java.lang.NullPointerException on a Windows machine when I try to open a socket for a second time after deleting the previous socket (stacktrace see image).

I can reproduce this with the provided demo echoServer by calling it first

``` matlab
x = echoServer(30000)
```

and opening the client2.html file. The websocket connects. After closing the connection via the website I delete the object in MATLAB.

``` matlab
delete(x)
```

When I try to open a new websocket by

``` matlab
y = echoServer(30000)
```

I get the following error _everytime_.

![screenshot 1](https://cloud.githubusercontent.com/assets/12747197/8284360/c86edac4-18fc-11e5-9b53-cb8249da9fee.png)

This hasn't happened on a Unix machine so far.

**Update**:  
Using a different port everytime a new websocket is established seems to work. I really would like to have the port static on the client side. Does MATLAB lock the port somehow?

**Comment by jebej** [comment] 2015-06-22 15:42
I thought I saw that this was an issue with the Java-Websocket library, but I can't seem to find that information again. As you have probably noticed, if you restart MATLAB, you can start the server just fine. It could thus also have to do with java objects not being properly cleaned up by MATLAB. Running `clear java` does not help though, and I am not sure what else to do on the MATLAB side.

Unfortunately, I am not proficient enough in Java to debug that issue.

Edit: It is indeed an issue with the port not being freed properly. You can easily test that in matlab by trying to start a TCP server on the same port:

``` matlab
>>  tcpipServer = tcpip('0.0.0.0',30000,'NetworkRole','Server');
>>  fopen(tcpipServer);
Error using icinterface/fopen (line 83)
Unsuccessful open: Address already in use: JVM_Bind
```

I still can't tell whether the problem is Matlab or java-websocket.

**Comment by JAAdrian** [comment] 2015-06-22 15:55
Thanks for the reply!
I'll see how to circumvent this issue for my application.

EDIT:

Great way to fetch the error since the Java exception is hard to catch.
Unfortunately, I don't have a license for the _Instrument Control Toolbox_. I'll see if I can find a workaround.

Am 22.06.2015 um 17:42 schrieb Jeremy:

**Comment by jebej** [comment] 2017-04-02 17:49
This issue is now fixed.

**Closed as completed by jebej** 2017-04-02 17:49 UTC
